"""
WATERSCOPE-AI — API Pydantic Schemas
Defines Pydantic v2 data contracts for AI object detection, AI change detection,
satellite biophysical analysis, satellite temporal change, and system health checks.
Strictly returns API-relative URLs (/files/...) and prevents local absolute path leaks.
"""

from datetime import date
from typing import List, Optional, Literal, Tuple, Dict, Any
from pydantic import BaseModel, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────────────────────
# General & Health Schemas
# ─────────────────────────────────────────────────────────────────────────────
class HealthResponse(BaseModel):
    """Health check response contract."""
    status: str = Field(default="healthy", description="API operational health status")
    service: str = Field(default="WATERSCOPE-AI API", description="Service identifier")
    version: str = Field(default="1.0.0", description="API version")


class LocationCoordinates(BaseModel):
    """Geographic point coordinates."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Latitude in degrees (-90 to 90)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Longitude in degrees (-180 to 180)")


class AOIParameters(BaseModel):
    """Area of Interest definition centered around a point with degree buffer."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Center latitude (-90 to 90)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Center longitude (-180 to 180)")
    buffer: float = Field(default=0.05, gt=0.0, le=5.0, description="Degree buffer radius (default ~5.5km)")


# ─────────────────────────────────────────────────────────────────────────────
# 1. POST /api/v1/ai/analyze-image
# ─────────────────────────────────────────────────────────────────────────────
class AIAnalyzeImageRequest(BaseModel):
    """Request metadata for image analysis."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Observation latitude (-90 to 90)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Observation longitude (-180 to 180)")


class AIDetectionItem(BaseModel):
    """Individual object detection item."""
    class_name: str = Field(..., description="Detected class name (e.g. boat, person, car, etc.)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence score (0.0 to 1.0)")
    bbox: List[float] = Field(..., description="Bounding box [x1, y1, x2, y2]")

    @field_validator("bbox")
    @classmethod
    def validate_bbox(cls, v: List[float]) -> List[float]:
        if len(v) != 4:
            raise ValueError(f"Bounding box must contain exactly 4 coordinates [x1, y1, x2, y2], got {len(v)}")
        return v


class AIDetectionSummary(BaseModel):
    """Summary counts of detected items."""
    objects_detected: int = Field(default=0, ge=0, description="Total count of all detected objects")
    ponds_detected: int = Field(default=0, ge=0, description="Total count of water ponds detected")


class AIAnalyzeImageOutputs(BaseModel):
    """API-relative file URLs generated by image analysis."""
    annotated_image_url: Optional[str] = Field(
        default=None,
        description="API-relative URL path to the annotated image with visual bounding boxes (e.g. /files/ai/...)",
    )


class AIAnalyzeImageResponse(BaseModel):
    """Response contract for single image object detection."""
    success: bool = Field(default=True, description="Indicates whether analysis was successful")
    request_id: str = Field(..., description="Unique request tracking identifier")
    image_id: str = Field(..., description="Identifier of the processed image")
    location: LocationCoordinates = Field(..., description="Geographical location of the image")
    model: str = Field(..., description="Model name and weights version used for inference")
    detections: List[AIDetectionItem] = Field(default_factory=list, description="List of detected objects")
    summary: AIDetectionSummary = Field(..., description="Summary counts of detected objects")
    outputs: AIAnalyzeImageOutputs = Field(..., description="Generated relative output URLs")
    processing_time_ms: float = Field(..., ge=0.0, description="Inference pipeline execution latency in milliseconds")


# ─────────────────────────────────────────────────────────────────────────────
# 2. POST /api/v1/ai/change-detection
# ─────────────────────────────────────────────────────────────────────────────
class AIChangeDetectionRequest(BaseModel):
    """Request metadata for bi-temporal AI change detection."""
    latitude: Optional[float] = Field(default=None, ge=-90.0, le=90.0, description="Optional observation latitude")
    longitude: Optional[float] = Field(default=None, ge=-180.0, le=180.0, description="Optional observation longitude")


class AIChangeDetail(BaseModel):
    """Individual categorized change event or region."""
    type: str = Field(..., description="Change classification category name")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Classification confidence (0.0 to 1.0) or null if unavailable")


class AIChangeDetectionOutputs(BaseModel):
    """API-relative URLs for change detection products."""
    change_map_url: Optional[str] = Field(default=None, description="API-relative URL to change mask or panel")
    annotated_before_url: Optional[str] = Field(default=None, description="API-relative URL to annotated T0 image")
    annotated_after_url: Optional[str] = Field(default=None, description="API-relative URL to annotated T1 image")


class AIChangeDetectionResponse(BaseModel):
    """Response contract for bi-temporal AI change detection."""
    success: bool = Field(default=True, description="Indicates whether change detection ran successfully")
    request_id: str = Field(..., description="Unique request tracking identifier")
    change_detected: bool = Field(default=False, description="True if significant change was detected between T0 and T1")
    change_type: Optional[str] = Field(default=None, description="Primary detected change type")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Confidence of primary change detection")
    change_percentage: Optional[float] = Field(default=None, ge=0.0, le=100.0, description="Total changed surface percentage")
    changes: List[AIChangeDetail] = Field(default_factory=list, description="List of detected change details")
    outputs: AIChangeDetectionOutputs = Field(..., description="Generated relative output URLs")
    processing_time_ms: float = Field(..., ge=0.0, description="Processing time in milliseconds")


# ─────────────────────────────────────────────────────────────────────────────
# 3. POST /api/v1/satellite/analyze
# ─────────────────────────────────────────────────────────────────────────────
class SatelliteAnalyzeRequest(BaseModel):
    """Request contract for single-observation satellite analysis."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Center latitude of AOI (-90 to 90)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Center longitude of AOI (-180 to 180)")
    buffer: Optional[float] = Field(default=0.05, gt=0.0, le=5.0, description="Half-width buffer in degrees")
    start_date: Optional[date] = Field(default=None, description="Start date for scene query (YYYY-MM-DD)")
    end_date: Optional[date] = Field(default=None, description="End date for scene query (YYYY-MM-DD)")
    max_cloud: Optional[float] = Field(default=20.0, ge=0.0, le=100.0, description="Maximum allowed cloud cover percentage")

    @model_validator(mode="after")
    def validate_date_range(self):
        if self.start_date and self.end_date and self.start_date > self.end_date:
            raise ValueError(f"Invalid date range: start_date ({self.start_date}) cannot be after end_date ({self.end_date})")
        return self


class SceneMetadataSummary(BaseModel):
    """Metadata summary of the analyzed Sentinel-2 scene."""
    scene_id: str = Field(..., description="Unique Sentinel-2 scene identifier")
    date: str = Field(..., description="Acquisition date (YYYY-MM-DD)")
    cloud_cover: float = Field(..., ge=0.0, le=100.0, description="Cloud cover percentage (0-100)")
    acquisition_datetime: Optional[str] = Field(default=None, description="Full ISO acquisition timestamp")


class RasterIndexStats(BaseModel):
    """Summary statistics for a spectral index raster (NDVI/NDWI)."""
    mean: float = Field(..., description="Mean value across valid cells")
    min: float = Field(..., description="Minimum valid value")
    max: float = Field(..., description="Maximum valid value")
    std: Optional[float] = Field(default=None, description="Standard deviation across valid cells")


class SatelliteIndices(BaseModel):
    """Vegetation and water index statistical summaries."""
    ndvi: RasterIndexStats = Field(..., description="Normalized Difference Vegetation Index statistics")
    ndwi: RasterIndexStats = Field(..., description="Normalized Difference Water Index statistics")


class SatelliteAnalyzeOutputs(BaseModel):
    """API-relative URLs for single-observation raster products."""
    ndvi_raster_url: str = Field(..., description="API-relative URL path to NDVI GeoTIFF (/files/satellite/...)")
    ndwi_raster_url: str = Field(..., description="API-relative URL path to NDWI GeoTIFF (/files/satellite/...)")
    water_mask_url: Optional[str] = Field(default=None, description="API-relative URL path to classified binary water mask GeoTIFF")
    ndvi_url: Optional[str] = Field(default=None, description="Alias for ndvi_raster_url")
    ndwi_url: Optional[str] = Field(default=None, description="Alias for ndwi_raster_url")


class SatelliteAnalyzeResponse(BaseModel):
    """Response contract for satellite biophysical index analysis."""
    success: bool = Field(default=True, description="Indicates whether analysis was successful")
    request_id: str = Field(..., description="Unique request tracking identifier")
    location: Optional[LocationCoordinates] = Field(default=None, description="Observation location coordinates")
    aoi: AOIParameters = Field(..., description="Area of interest parameters")
    scene: SceneMetadataSummary = Field(..., description="Sentinel-2 scene metadata")
    indices: SatelliteIndices = Field(..., description="Computed NDVI and NDWI statistics")
    outputs: SatelliteAnalyzeOutputs = Field(..., description="Generated GeoTIFF product relative URLs")
    processing_time_ms: float = Field(..., ge=0.0, description="Pipeline processing time in milliseconds")


# ─────────────────────────────────────────────────────────────────────────────
# 4. POST /api/v1/satellite/change
# ─────────────────────────────────────────────────────────────────────────────
class SatelliteChangeRequest(BaseModel):
    """Request contract for multi-temporal satellite change detection."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Center latitude of AOI (-90 to 90)")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Center longitude of AOI (-180 to 180)")
    buffer: Optional[float] = Field(default=0.05, gt=0.0, le=5.0, description="Half-width buffer in degrees")
    before_date: Optional[date] = Field(default=None, description="Initial observation date T0 (YYYY-MM-DD)")
    after_date: Optional[date] = Field(default=None, description="Subsequent observation date T1 (YYYY-MM-DD)")

    @model_validator(mode="after")
    def validate_date_order(self):
        if self.before_date is not None and self.after_date is not None:
            if self.before_date >= self.after_date:
                raise ValueError("before_date must be strictly earlier than after_date")
        return self


class SceneObservationItem(BaseModel):
    """Summary of a specific temporal observation."""
    date: str = Field(..., description="Acquisition date (YYYY-MM-DD)")
    scene_id: str = Field(..., description="Sentinel-2 scene product ID")


class NDVIChangePercentages(BaseModel):
    """Vegetation change distribution percentages."""
    gain_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of valid cells with vegetation gain")
    loss_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of valid cells with vegetation loss")
    stable_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of valid cells with stable vegetation")


class NDWIChangePercentages(BaseModel):
    """Surface water dynamic category percentages."""
    water_gain_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of cells with water gain / inundation")
    water_loss_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of cells with water loss / drying")
    stable_percent: float = Field(..., ge=0.0, le=100.0, description="Percentage of cells with stable water or persistent land")


class SatelliteChangeOutputs(BaseModel):
    """API-relative URLs for temporal change GeoTIFF products."""
    ndvi_change_raster_url: Optional[str] = Field(default=None, description="Relative URL to NDVI difference GeoTIFF")
    ndwi_change_raster_url: Optional[str] = Field(default=None, description="Relative URL to NDWI difference GeoTIFF")
    water_change_raster_url: Optional[str] = Field(default=None, description="Relative URL to classified water dynamics GeoTIFF")
    ndvi_classified_raster_url: Optional[str] = Field(default=None, description="Relative URL to classified NDVI dynamics GeoTIFF")
    ndwi_classified_raster_url: Optional[str] = Field(default=None, description="Relative URL to classified NDWI dynamics GeoTIFF")
    summary_json_url: Optional[str] = Field(default=None, description="Relative URL to change statistics JSON")


class SatelliteChangeResponse(BaseModel):
    """Response contract for multi-temporal satellite change detection."""
    success: bool = Field(default=True, description="Indicates whether the request was evaluated")
    request_id: str = Field(..., description="Unique request tracking identifier")
    status: Literal["completed", "unavailable", "pending"] = Field(
        default="completed",
        description="Processing status: 'completed' when two observations exist, 'unavailable' when second scene missing",
    )
    location: Optional[LocationCoordinates] = Field(default=None, description="Observation location coordinates")
    aoi: AOIParameters = Field(..., description="Target Area of Interest parameters")
    before: Optional[SceneObservationItem] = Field(default=None, description="Initial observation T0 metadata")
    after: Optional[SceneObservationItem] = Field(default=None, description="Subsequent observation T1 metadata")
    before_scene: Optional[SceneObservationItem] = Field(default=None, description="Initial observation T0 metadata alias")
    after_scene: Optional[SceneObservationItem] = Field(default=None, description="Subsequent observation T1 metadata alias")
    changes: Optional[Dict[str, Any]] = Field(default=None, description="Detailed change statistics and categories")
    ndvi_change: Optional[NDVIChangePercentages] = Field(default=None, description="Vegetation change distribution")
    ndwi_change: Optional[NDWIChangePercentages] = Field(default=None, description="Water dynamics distribution")
    outputs: Optional[SatelliteChangeOutputs] = Field(default=None, description="Generated temporal GeoTIFF relative URLs")
    processing_time_ms: float = Field(default=0.0, ge=0.0, description="Pipeline processing time in milliseconds")
    notice: Optional[str] = Field(default=None, description="Informational notice if second observation is unavailable")
